(module
  (type $0 (func))
  (type $1 (func))
  (type $2 (func))
  (import "e" "a" (func $0 (type 1)))
  (import "e" "f" (func $1 (type 2)))
  (func $2 (type 0) (nop))
  (func $3 (type 0) (block))
  (func $4 (type 0) (call 3))
  (func $5 (type 1) (call 2))
  (func $6 (type 1) (call 0) (call 5))
  (func $7 (type 2) (call 4) (call 6) (call 1))
  (func $8 (type 0) (call 2) (call 1))
  (export "k" (func 7))
  (start 8)
)
